version: '3'

services:
  dozzle:
    # A container that exposes an API to show its IP address
    image: amir20/dozzle
    labels:
      - "traefik.http.routers.dozzle.rule=Host(`dozzle.docker.localhost`)"
      - "traefik.enable=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  monica:
    image: monica
    labels:
      - "traefik.http.routers.monica.rule=Host(`monica.docker.localhost`)"
      - "traefik.enable=true"
      - "traefik.http.services.monica.loadbalancer.server.port=80"

  openspeedtest:
    image: openspeedtest/latest
    labels:
      - "traefik.http.routers.openspeedtest.rule=Host(`openspeedtest.docker.localhost`)"
      - "traefik.enable=true"
      - "traefik.http.services.openspeedtest.loadbalancer.server.port=8080"


networks:
  default:
    name: hid_net
    external: true
